### ISSUE TITLE
Getting Error of 'Key is not valid' for SWIFT version of iOS SDK

### ISSUE THREAD

**Issue by munjalpandya** [payu-intrepos/PayUMoney-IOS-SDK#11]
We have implemented the swift version of iOS SDK, but at in the PayU screen it is giving error of '**Key is not valid**'.

We are passing the test environment key which we have used for Android SDK. In Android it is working proper.

Key passed for testing is '**gtKFFx**' 

In case any one has idea about this error, please let us know.
![simulator screen shot may 25 2017 3 15 15 pm](https://cloud.githubusercontent.com/assets/8926956/26448725/43888e64-416c-11e7-88d8-80d617238324.png)

**Comment by DishaMukherjee** [comment]
**'Key is not valid' error is occurring because you are not using correct key.**

Below is the link for downloading the required integration kit: 
https://github.com/payu-intrepos/PayUMoney-IOS-SDK/tree/master/PlugNPlay/Objective-C%20SampleApp 
-->> For the test environment:

merchant-key: 40747T 
merchant-id: 396132 
Salt: cJHb2BC9 

Below is the test card details for doing a test transaction in the testing mode. 
Card No - 5123456789012346 
Expiry - 05/2020 
CVV - 123 
Name - Test

**Comment by amberkatyal** [comment]
Hi,
I am getting still the same error on using above credentials. I followed the documentation. I am generating hash locally in iOS.

**Comment by sharathfantain** [comment]
Facing the sam issue in iOS... Do you have any answer? Kindly reopen the issue

**Comment by udayeega** [comment]
Anyone solved this issue. Please tell me.
