### ISSUE TITLE
iOS Build for testflight using test credentials

### ISSUE THREAD

**Issue by hemanth2k13** [payu-intrepos/PayUMoney-IOS-SDK#5]
Hi, I integrated the SDK and followed sample app to link to my Swift code, integration was successful and i was able to launch PayU in simulator and iPhone too. But when i tried to upload the same for testflight/app store i am getting errors.
![screen shot 2017-02-08 at 11 40 09 pm](https://cloud.githubusercontent.com/assets/20104424/22796595/f504f8b0-ef20-11e6-8b07-5aaa34e23d22.png)
I couldn't find any related issues in payu, how ever found it in some other frameworks but no real fixes.
How can i fix this?

**Comment by vipin04** [comment]
Hi @hemanth2k13,
Thanks for reporting the issue.

The problem seems to be due to fat binary we are shipping with the framework.

The problem is if we ship framework containing object code for only device (arm7, arm64), then you will not be able to run your app on simulator.
So we have to ship the framework containing slices for every architecture: arm7, arm64, i386, x86_64. The last two architecture corresponds to simulator.

Apple has started complaining if app contains simulator architectures. There is a quick fix to this issue. 
**Note: After doing following steps, you will not be able to run app on simulator. Do it just before deploying the app on Testflight**

1. Go inside the PayUmoney_SDK.framework folder from terminal.
2. Run following commands

`lipo -remove i386 PayUmoney_SDK -o PayUmoney_SDK`
`lipo -remove x86_64 PayUmoney_SDK -o PayUmoney_SDK`

Now the binary is _thinned_

I know the solution is not very elegant. We are making a script which should automate this process for merchants. Kindly bear with until then.
Let me know with your outcome.

**Comment by hemanth2k13** [comment]
Hi Vipin,
Thanks for the response.
I just found this solution and it worked perfectly. Now i can use same sdk for both simulator and device.
See if this link is helpful.

http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/
